### PR TITLE
Any "customized" components in the future?

### PR DESCRIPTION
**Pull request by Shawn-Fan**
Awesome sample project including legend, search, and basemap selection. Do you have plan to develop new "legend component" like user can select and display selected layers, "search component" ... in the future?

### CODE REVIEW

**Comment by tomwayson** [comment]
Thank you.

I have no plans to develop any more components for the example app. This is not really intended to be used as an application boilerplate, or starting point. 

It's main purpose is to illustrate loading esri modules and some ways for esri and custom components to communicate. I would welcome any contributions that help illustrate those techniques.

**Comment by Shawn-Fan** [comment]
Hi Tom,
Thanks for your response.

I am working on "Toggle layer Visibility" component and it will be finished soon. How can I upload it and discuss it with you?

**Comment by tomwayson** [comment]
If you are developing that component w/in the context of this app, you can make a pull request to this repo. I'd be glad to review it and merge it if it makes sense in this repo.

However, if it's something that you intend to be reusable, it's probably best in the long run to put it in it's own repo that others can npm install into their own apps.

**Comment by Shawn-Fan** [comment]
Thanks, I'll follow your style and the context of this app. 
1. Some codes added to "app.component.ts"
2. A new component "LayersVisibilitySelect.component.ts" added.
3. Some codes added to "map.service.ts"

I'll make a pull request after everything is done.

**Pull request closed without merging**
