### PR TITLE
Webpack2 angular2 esri

### PR DESCRIPTION
**Pull request by hassanqaiser**
arcgis-js-api usage with webpack2-angular2. arcgis-js-api was
configured with webpack1. this example shows how you can use
arcgis-js-api with webpack2. Please refer to readme for the steps used
to migrate from webpack1 to webpack2.

### CODE REVIEW

**Comment by tomwayson** [comment]
@hassanqaiser 

This is great. I pulled and ran your code. It seems to work for the most part, though the map was not taking up the full height of the page and I would see this HMR error when ever I made a change to the source files:

image

However I can see that you're brining in most, if not all of the Angular Class repo, and as excited as I am to get webpack2, HMR, and all the other goodies (like karma unit tests) that are part of that repo into this one, I'm not sure that it's a good idea for me to merge all of that. As far as tooling is concerned, the purpose of this repo is to demonstrate _just the configuration needed_ to get the ArcGIS API for JavaScript running in an Angular2 app. I don't want to confuse people by introducing all the other sophisticated tooling that is is part of that repo.

That said, I think it would be _very_ valuable to have an example of the ArcGIS API for JavaScript working with the Angular Class starter. What I propose is that you just make a new repository called "webpack2-angular2-esri" or "angular2-webpack-esri-starter", or whatever you like and copy the contents of your [webpack2-angular2-esri branch](https://github.com/hassanqaiser/angular2-esri-example/tree/webpack2-angular2-esri) into that repository. Once you do that, I can create a link from the README of this repository to that one for anyone that wants to start with all the tooling included in the Angular Class starter.

What do you think?

I'd also likely open a seperate issue here to upgrade to webpack2 w/o all the other configuration settings included in that repo and copy just the webpack2 configuration settings from your new repo.

**Comment by hassanqaiser** [comment]
@tomwayson thats good idea. I will create new repo and will send you the link shortly... thanks

**Comment by hassanqaiser** [comment]
@tomwayson  please find the link with new repository.

https://github.com/hassanqaiser/angular2_webpack2_esri

Thanks,

**Comment by tomwayson** [comment]
@hassanqaiser 

Great! I've closed out #27 by linking to your repo and have [added a link to the README](https://github.com/tomwayson/angular2-esri-example#resources)

Thanks again for sharing this.

**Pull request closed without merging**
