### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by Shawn-Fan**
pull request

### CODE REVIEW

**Comment by Shawn-Fan** [comment]
pull request for app.component.ts
                          map.service.ts
                          layer.component.ts

**Comment by tomwayson** [comment]
Is this the pull request you are referring to in #6?

Did you mean to close this?

If you would like me to review, please reopen it.

**Comment by Shawn-Fan** [comment]
Sorry About that . It is open now

**Comment by tomwayson** [comment]
@Shawn-Fan 

Thank you for this. It looks like this does not include the code to load the layer component into the application. I tried modifying the app component to include your layer component in place of the legend, however, I am getting an error. Can you please include the code needed to do that?

**Comment by Shawn-Fan** [comment]
```
 this.basemapSelect.selectedBasemap = response.basemapName;
  // bind the map title
  this.title = response.itemInfo.item.title;
```
-    //bind the legendlayer
-    this.LayerComponent.init(response);
  }
  
  ......

Above 2 lines is the codes. I am so sorry maybe something wrong in the "pull request", Please let me know if it works.

**Comment by tomwayson** [comment]
When I pull and run your code as is, I get the following error in the console: "TypeError: Cannot read property 'init' of undefined" at the above line. I don't see anywhere in app.component.ts where you define `this.LayerComponent`.

I was able to get it working and have made a [pull request to your master branch w/ the changes needed to get load the layer list](https://github.com/Shawn-Fan/angular2-esri-example/pull/1/files). You can either merge that pull request, or make similar changes yourself and then push to your master. Once you do that, this pull request will be updated with the changes and I can merge.

**Comment by Shawn-Fan** [comment]
I'll try to do it again.

**Comment by Shawn-Fan** [comment]
I updated the app.component.ts again.Please check it.

**Comment by tomwayson** [comment]
@Shawn-Fan 

Thank you for this contribution!

**Pull request merged**
